language: objective-c
os: osx
osx_image: xcode7.3

env:
  matrix:
    - TEST_TYPE=iOS
before_install:
- |
    gem install xcpretty -N --no-ri --no-rdoc

script:
- |
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild clean test -project NTYAmrConverter.xcodeproj -scheme NTYAmrConverter -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" -enableCodeCoverage YES | xcpretty
    fi
after_success:
- |
    if [ "$TEST_TYPE" = iOS ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
